In [133]:
# Determine the five most common journals and the total articles for each.
import pandas as pd

In [134]:
data = pd.read_csv("/Users/harshini/Desktop/Thinkful/Data/book.csv", encoding = "ISO-8859-1")
data.head()

,PMID/PMCID,Publisher,Journal title,Article title,COST (£) charged to Wellcome (inc VAT when charged)
0,NaN,CUP,Psychological Medicine,Reduced parahippocampal cortical thickness in ...,£0.00
1,PMC3679557,ACS,Biomacromolecules,Structural characterization of a Model Gram-ne...,£2381.04
2,23043264 PMC3506128,ACS,J Med Chem,"Fumaroylamino-4,5-epoxymorphinans and related ...",£642.56
3,23438330 PMC3646402,ACS,J Med Chem,Orvinols with mixed kappa/mu opioid receptor a...,£669.64
4,23438216 PMC3601604,ACS,J Org Chem,Regioselective opening of myo-inositol orthoes...,£685.88

In [135]:
top5_list = list(data['Journal title'].value_counts().index[0:5])
top5_list

['PLoS One',
 'PLoS ONE',
 'Journal of Biological Chemistry',
 'Nucleic Acids Research',
 'Proceedings of the National Academy of Sciences']

In [136]:
group_jour = data.groupby('Journal title').count()
group_jour.head()

,PMID/PMCID,Publisher,Article title,COST (£) charged to Wellcome (inc VAT when charged)
Journal title,,,,
ACS Chemical Biology,4,5,5,5
ACS Chemical Neuroscience,1,1,1,1
ACS NANO,1,1,1,1
ACS Nano,1,1,1,1
ACTA F,1,1,1,1

In [137]:
top = group_jour.loc[top5_list,'Article title']
top_df = pd.DataFrame()
top_df['Top 5 Journals'] = top.index
top_df['Article count']=list(top)
top_df

                                    Top 5 Journals  Article count
0                                         PLoS One             92
1                                         PLoS ONE             62
2                  Journal of Biological Chemistry             48
3                           Nucleic Acids Research             21
4  Proceedings of the National Academy of Sciences             19

In [155]:
data['COST (£) charged to Wellcome (inc VAT when charged)'] = data['COST (£) charged to Wellcome (inc VAT when charged)'].str.replace('£','')
data.head()

,PMID/PMCID,Publisher,Journal title,Article title,COST (£) charged to Wellcome (inc VAT when charged)
0,NaN,CUP,Psychological Medicine,Reduced parahippocampal cortical thickness in ...,0.00
1,PMC3679557,ACS,Biomacromolecules,Structural characterization of a Model Gram-ne...,2381.04
2,23043264 PMC3506128,ACS,J Med Chem,"Fumaroylamino-4,5-epoxymorphinans and related ...",642.56
3,23438330 PMC3646402,ACS,J Med Chem,Orvinols with mixed kappa/mu opioid receptor a...,669.64
4,23438216 PMC3601604,ACS,J Org Chem,Regioselective opening of myo-inositol orthoes...,685.88

In [161]:
#data['COST (£) charged to Wellcome (inc VAT when charged)'].astype(float)
data['COST (£) charged to Wellcome (inc VAT when charged)'] = pd.to_numeric(data['COST (£) charged to Wellcome (inc VAT when charged)'],errors='coerce')

In [192]:
data.head()
data['Journal title'].value_counts()

PLoS One                                               92
PLoS ONE                                               62
Journal of Biological Chemistry                        48
Nucleic Acids Research                                 21
Proceedings of the National Academy of Sciences        19
Human Molecular Genetics                               18
PLoS Neglected Tropical Diseases                       18
Nature Communications                                  17
PLoS Pathogens                                         15
Neuroimage                                             15
PLoS Genetics                                          15
Brain                                                  14
BMC Public Health                                      14
NeuroImage                                             14
PLOS ONE                                               14
Movement Disorders                                     13
Journal of Neuroscience                                12
Biochemical Journal                                    12
Developmental Cell                                     12
Journal of General Virology                            11
BMJ                                                    10
PLOS One                                               10
Current Biology                                        10
Neuron                                                  9
Cell Reports                                            9
Neurobiology of Aging                                   8
Malaria Journal                                         8
Journal of Structural Biology                           8
European Journal of Immunology                          8
Journal of Clinical Endocrinology and Metabolism        8
                                                       ..
Rapid Communications in Mass Spectrometry               1
Frontiers in Molecular Neuroscience                     1
Acta Diabetologica                                      1
History Workshop Journal                                1
Cell Death Differentiation                              1
Molecular Biology                                       1
Journal of the American College of Cardiology           1
Americal Journal of Psychiatry                          1
American Journal of Psychiatry                          1
Mol Pharm                                               1
Acta Crystallographica, Section D                       1
Int J Epidemiol                                         1
Journal of Medical Virology                             1
ACS Nano                                                1
JOURNAL OF BACTERIOLOGY                                 1
Clinical Genetics                                       1
Neuroscience                                            1
Evolutionary Applications                               1
J Immunol                                               1
International Journal of Stroke                         1
International Journal of Experimental Pathology         1
Journal of Clinical Microbiology                        1
Molecular and Cellular Biology                          1
Jnl of the International Neuropsychological Society     1
Journal of Neuroinflammation                            1
Cognitive Therapy and Research                          1
Journal of Archaeological Science                       1
The Journal of Physiology                               1
Journal of Neuroscience                                 1
Microbes Infect                                         1
Name: Journal title, Length: 984, dtype: int64

In [195]:
mean = data.groupby('Journal title').mean()
median = data.groupby('Journal title').median()
std = median = data.groupby('Journal title').std()